sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

arch:
  packages:
    - ansible
  script:
    - "ansible-playbook -i inventory/hosts.example octoprint_setup/octoprint_setup.yml --syntax-check"
    - "sudo ansible-playbook -i inventory/hosts.example octoprint_setup/octoprint_setup.yml"
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
