---
- name: Instalación de Octoprint sobre una Pi con Arch
  hosts: all
  vars:
    octo_path: "{{ ansible_env.HOME }}/Octoprint-git"
  tasks:
    - pacman:
        name: "{{ item }}"
        state: installed
      with_items:
        - git
        - vim
        - sudo
        - screen
        - python2-virtualenv
        - networkmanager
        - python-pip
        - gcc
        - curaengine
        - yajl
        - pkg-config
        - make
        - fakeroot
        - linux-raspberrypi-headers
      become: yes
    - pacman:
        name: "{{ item }}"
        state: absent
      with_items:
        - network
      become: yes
    - name: Starts and enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - NetworkManager
      become: yes
      ignore_errors: true
    - name: Descarga octoprint
      git:
        repo: https://github.com/foosel/OctoPrint.git
        dest: "{{ octo_path }}"
        update: yes
    - name: Instala venv de python
      command: /usr/bin/virtualenv2 {{ octo_path }}/venv
      args:
        chdir: "{{ octo_path }}"
    - name: Ejecuta setup.py dentro del ambiente venv
      command: ./venv/bin/python setup.py install
      args:
        chdir: "{{ octo_path }}"
