---
- name: Instalación de Octoprint sobre una Pi con Arch
  hosts: all
  vars:
    octo_path: "{{ ansible_env.HOME }}/Octoprint-git"
  tasks:
    - pacman:
        name: "{{ item }}"
        state: installed
      with_items:
        - git
        - vim
        - sudo
        - screen
        - python2-virtualenv
      become: yes
    - name: Descarga octoprint
      git:
        repo: https://github.com/foosel/OctoPrint.git
        dest: "{{ octo_path }}"
    - name: Instala venv de python
      command: /usr/bin/virtualenv2 {{ octo_path }}/venv
      args:
        chdir: "{{ octo_path }}"
    - name: Ejecuta setup.py dentro del ambiente venv
      command: ./venv/bin/python setup.py install
      args:
        chdir: "{{ octo_path }}"
